local-simulation:
  user-workflow:
    workflow-name: "x402-facilitator"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"

staging:
  user-workflow:
    workflow-name: "x402-facilitator"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"

production:
  user-workflow:
    workflow-name: "x402-facilitator"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"

